### ISSUE TITLE
Would you mind adding a few examples please sorry to bother you.

### ISSUE THREAD

**Issue by Insticthere** [arifer612/MDLPackage#1]
if possible i would like some examples with this api espciall `mdl.exportMDL` a i would want to learn how to export it in filex thank you for working on it anyways

**Comment by arifer612** [comment]
Well to be honest, this project was my very first Python Project and I just made it for fun to learn the language so I did not put that much effort into it. I was planning on re-structuring it into a proper pseudo-API package in the near future (definitely with better documentation than this) so it may be better to check it out then.

**Comment by Insticthere** [comment]
> Well to be honest, this project was my very first Python Project and I just made it for fun to learn the language so I did not put that much effort into it. I was planning on re-structuring it into a proper pseudo-API package in the near future (definitely with better documentation than this) so it may be better to check it out then.

i see thats fine thanks for the response btw will look forward to a proper api or library!
